import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import {useFrame, useThree} from '@react-three/fiber';
import walk_scene from '../../assets/hobby/Walk-model.glb';
import {a} from '@react-spring/three';
import RotationSetting from "../../RotationSettings.jsx";
import AutoRotationSetting from "../../AutoRotationSetting.jsx";

const Walk = ({isRotating, setIsRotating, ...props}) => {
    const walkRef = useRef();
    const {gl, viewport} = useThree();
    const { nodes, materials } = useGLTF(walk_scene)

    AutoRotationSetting(walkRef, isRotating, setIsRotating, viewport)

    return (
        <a.group ref={walkRef} {...props} dispose={null}>
            <mesh
                geometry={nodes.Sphere.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Icosphere.geometry}
                material={materials['Material.007']}
            />
            <mesh
                geometry={nodes.Icosphere001.geometry}
                material={materials['Material.007']}
            />
            <mesh
                geometry={nodes.Cube022.geometry}
                material={materials['Material.003']}
            />
            <mesh
                geometry={nodes.Cube022_1.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Cube022_2.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Cube022_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube022_4.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Cube022_5.geometry}
                material={materials['SVGMat.023']}
            />
            <mesh
                geometry={nodes.Sphere001_1.geometry}
                material={materials['Material.006']}
            />
            <mesh
                geometry={nodes.Sphere001_2.geometry}
                material={materials['SVGMat.001']}
            />
            <mesh
                geometry={nodes.Cone004.geometry}
                material={materials['Material.006']}
            />
            <mesh
                geometry={nodes.Cone004_1.geometry}
                material={materials['SVGMat.001']}
            />
            <mesh
                geometry={nodes.Cone006.geometry}
                material={materials['Material.006']}
            />
            <mesh
                geometry={nodes.Cone006_1.geometry}
                material={materials['SVGMat.001']}
            />
            <mesh
                geometry={nodes.Sphere008.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Sphere008_1.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Sphere008_2.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Sphere008_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube026.geometry}
                material={materials['Material.003']}
            />
            <mesh
                geometry={nodes.Cube026_1.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Cube026_2.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Cube026_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube026_4.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Cube026_5.geometry}
                material={materials['SVGMat.023']}
            />
            <mesh
                geometry={nodes.Sphere010.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Sphere010_1.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Sphere010_2.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Sphere010_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube027.geometry}
                material={materials['Material.003']}
            />
            <mesh
                geometry={nodes.Cube027_1.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Cube027_2.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Cube027_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube027_4.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Cube027_5.geometry}
                material={materials['SVGMat.023']}
            />
            <mesh
                geometry={nodes.Sphere011.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Sphere011_1.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Sphere011_2.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Sphere011_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube028.geometry}
                material={materials['Material.003']}
            />
            <mesh
                geometry={nodes.Cube028_1.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Cube028_2.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Cube028_3.geometry}
                material={materials.Material}
            />
            <mesh
                geometry={nodes.Cube028_4.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Cube028_5.geometry}
                material={materials['SVGMat.023']}
            />
            <mesh
                geometry={nodes.Sphere012.geometry}
                material={materials['SVGMat.022']}
            />
            <mesh
                geometry={nodes.Sphere012_1.geometry}
                material={materials['Material.001']}
            />
            <mesh
                geometry={nodes.Sphere012_2.geometry}
                material={materials['Material.004']}
            />
            <mesh
                geometry={nodes.Sphere012_3.geometry}
                material={materials.Material}
            />
        </a.group>
    )
}

export default Walk;
